---
version: '3.4'
services:
  mysql:
    deploy:
      restart_policy:
        condition: "on-failure"
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_SECRET}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_SECRET}  
    network_mode: "service:fbctf"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      database:
        aliases:
          - mysql


  db_archive:
    deploy:
      restart_policy:
        condition: "on-failure"
    image: blacklabelops/volumize:latest
    volumes:
      - dbdata:/var/lib/mysql:ro
      - backupdata:/backup
    environment:
      VOLUMERIZE_SOURCE=/var/lib/mysql
      VOLUMEIZE_TARGET=file:///backup
      VOLUMEIZE_JOBBER_TIME="@weekly"
        
  memcached:
    restart: always 
    image: memcached:latest
    network_mode: "service:fbctf"
     
  fbctf:
    deploy:
      restart_policy:
        condition: "on-failure"
    image: alexgaspar/fbctf:latest
    network_mode: "bridge"
    links:
      - memcached:memcached
      - mysql:mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_SECRET}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_SECRET}
      - MEMCACHED_PORT=11211
      - SSL_SELF_SIGNED=true
      - VIRTUAL_HOST=ctf.dallasmakerspace.org
      - VIRTUAL_PORT=80
    networks:
      - database
      - bridge

networks:
  database:
  bridge:
    external:
      name: bridge
      
volumes:
  dbdata: {}
  backupdata: {}
