---
version: '3.4'
services:
  mysql:
    restart: always
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_SECRET}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_SECRET}  
    network_mode: "service:fbctf"
    networks:
      database:
        aliases:
          - mysql

  memcached:
    restart: always 
    image: memcached:latest
    network_mode: "service:fbctf"
     
  fbctf:
    restart: always
    image: alexgaspar/fbctf:latest
    network_mode: "bridge"
    links:
      - memcached:memcached
      - mysql:mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_SECRET}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_SECRET}
      - MEMCACHED_PORT=11211
      - SSL_SELF_SIGNED=true
      - VIRTUAL_HOST=ctf.communitygrid.dallasmakerspace.org
      - VIRTUAL_PORT=80
    networks:
      - database
      - bridge

networks:
  database:
  bridge:
    external:
      name: bridge
